### ISSUE TITLE
Corruption as data augmentation?

### ISSUE THREAD

**Issue by ShawnNew** [bethgelab/imagecorruptions#14]
Hi, thanks very much for your awesome work!

I am just wondering why don't you suggest using this corruption as data augmentation when training detection deep neural network? Is it only because the process time is kind of long?

Thanks again.

**Comment by rgeirhos** [comment]
Sorry for the late reply. You can always include specific corruption types during training, but this won't guarantee robustness towards unseen distortions (which can be tested using imagecorruptions).

**Comment by Hvitgar** [comment]
Hey @gionanide, the main focus of this package is to test your trained image classification model's performance on distorted test data. The workflow we used was to corrupt our test data and then measure classification performance.

For object detection tasks, this package is integrated into the [mmdetection](https://github.com/open-mmlab/mmdetection) framework. Corruptions are not applied to ground truth images in that framework. 

If you interpret the corruptions in this package as naturally occuring image distortions (weather, lens flare, ...), this would not change where the percepted object is _in the real world_, so from that standpoint it doesn't really make sense to alter ground truth, but that's totally up to you and your task.

If you want to use this package in your own pipeline in order to "corrupt" your ground truth images too, note that some corruptions are not deterministic, so you'd have to fix seeds in order to get the same corruption for the image and the ground truth image.

**Comment by gionanide** [comment]
Hello @Hvitgar, thank you very much for your quick answer.
